export const SET_ORGANIZATION_NAME = "SET_ORGANIZATION_NAME";
export const GET_ORGANIZATION_NAME = "GET_ORGANIZATION_NAME";

export const SET_CONTRIBUTORS_ORG = "SET_CONTRIBUTORS_ORG";
export const GET_CONTRIBUTORS_ORG = "GET_CONTRIBUTORS_ORG";

export const SET_REPOSITORIES_ORG = "SET_REPOSITORIES_ORG";
export const GET_REPOSITORIES_ORG = "GET_REPOSITORIES_ORG";

export const SET_SELECTED_CONT_NAME = "SET_SELECTED_CONT_NAME";
export const GET_SELECTED_CONT_NAME = "GET_SELECTED_CONT_NAME";

export const SET_SELECTED_REPO_NAME = "SET_SELECTED_REPO_NAME";
export const GET_SELECTED_REPO_NAME = "GET_SELECTED_REPO_NAME";